apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: urban-influx
  namespace: myproject
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: hhiden/influx:latest
