apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: urbanevents-subscription
  namespace: myproject
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: urbanchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: urban-influx

